### ISSUE TITLE
Feature request: Jump to end of interpreted region

### ISSUE THREAD

**Issue by mizlan** [tomtomjhj/vscoq.nvim#1]
I'd like for there to be a function/command to jump to the end of the interpreted region, similar to what CoqJumpToEnd does in Coqtail.

**Comment by tomtomjhj** [comment]
thanks for suggestion. added: https://github.com/tomtomjhj/vscoq.nvim/commit/0691ba702e57826ba9e44d1016c59d3b8a4f8d51
